ADSDataDirect.Web/Controllers/NotificationController.cs
using System;
using System.Linq;
using System.Data.Entity;
using System.Globalization;
using System.Web.Mvc;
using ADSDataDirect.Core.Entities;
using ADSDataDirect.Enums;
using ADSDataDirect.Web.Helpers;
using ADSDataDirect.Web.Models;
using PagedList;
using ADSDataDirect.Infrastructure.Db;

namespace ADSDataDirect.Web.Controllers
{
    [Authorize]
    public class NotificationController : BaseController
    {
        // Notification
        public ActionResult Index(NotificationSearchVm sc)
        {
            var notifications = Db.Notifications
                .Where(x => x.Status == (int)NotificationStatus.Found);

            if (!string.IsNullOrEmpty(sc.BasicOrderNumber))
            {
                notifications = notifications.Where(s => s.CampaignId.ToString() == sc.BasicOrderNumber);
            }

            if (!string.IsNullOrEmpty(sc.OrderedFrom))
            {
                DateTime dateFrom = DateTime.ParseExact(sc.OrderedFrom, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                notifications = notifications.Where(s => s.FoundAt >= dateFrom.Date);
                ViewBag.OrderedFrom = sc.OrderedFrom;
            }
            if (!string.IsNullOrEmpty(sc.OrderedTo))
            {
                DateTime dateTo = DateTime.ParseExact(sc.OrderedTo, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                notifications = notifications.Where(s => s.FoundAt <= dateTo.Date);
                ViewBag.OrderedTo = sc.OrderedTo;
            }

            var notificationVms = notifications.OrderByDescending(x => x.CreatedAt).ToList().Select(x =>
                new NotificationVm()
                {
                    Id = x.Id.ToString(),
                    CampaignId = x.CampaignId.ToString(),
                    OrderNumber = x.OrderNumber,
                    SegmentNumber = x.SegmentNumber,
                    CampaignName = Db.Campaigns.Include(y => y.Approved).FirstOrDefault(y => y.Id == x.CampaignId)
                        ?.Approved.CampaignName,
                    QcRule = x.QcRule,
                    QcRuleString = Enum.GetName(typeof(QcRule), x.QcRule),
                    Message = x.Message,
                    FoundAt = x.FoundAt?.ToString(StringConstants.TimeStampFormat),
                    Status = Enum.GetName(typeof(NotificationStatus), x.Status)
                });

            ViewBag.BasicOrderNumber = OrderNumberList;

            // Paging
            int pageNumber = (sc.Page ?? 1);
            return View(notificationVms.ToPagedList(pageNumber, PageSize));
        }

        public ActionResult Settings()
        {
            SettingsVm sc = SettingsManager.Instance.LoadSettings(Db);
            string view = IsNxs ? "SettingsNXS" : "Settings";
            return View(view, sc);
        }

        [HttpPost]
        public ActionResult Settings(SettingsVm sc)
        {
            SettingsManager.Instance.SaveSettings(Db, sc);
            TempData["Success"] = "Notification Settings has been saved sucessfully.";
            return RedirectToAction("Settings");
        }

    }
}

ADSDataDirect.Web/Views/Notification/Index.cshtml
@using ADSDataDirect.Core.Entities
@using ADSDataDirect.Enums
@using ADSDataDirect.Web.Helpers
@using PagedList.Mvc
@model PagedList.IPagedList<ADSDataDirect.Web.Models.NotificationVm>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string currentSort = ViewBag.CurrentSort;
    if (string.IsNullOrEmpty(currentSort))
    {
        currentSort = "OrderNumber_desc";
    }

    var columnSortParams1 = new { sortOrder = ViewBag.OrderNumberSortParm };
    var columnSortParams2 = new { sortOrder = ViewBag.CampaignNameSortParm };
    var columnSortParams3 = new { sortOrder = ViewBag.CreatedBySortParm };
    var columnSortParams4 = new { sortOrder = ViewBag.CreatedAtSortParm };
    var columnSortParams5 = new { sortOrder = ViewBag.BroadcastDateSortParm };
    var columnSortParams6 = new { sortOrder = ViewBag.QuantitySortParm };
    var columnSortParams7 = new { sortOrder = ViewBag.StatusSortParm };

    var loggedInUser = Session["user"] as WfpUser;
    var isLoggedIn = loggedInUser != null;
    var isAdmin = loggedInUser != null && (loggedInUser.UserType == (int)UserType.Admin);
}

<form id="frmSearch" method="post">
    <div class="row" style="margin-top: 5px">
        <div class="col-md-5">
            <div class="headertab">
                Tracking Notifications
            </div>
        </div>
        <div class="col-md-2 no-left-padding " data-tooltip="tooltip" title="Search">
            @Html.DropDownList("BasicOrderNumber", null, htmlAttributes: new { @class = "form-control", @id = "basicOrderNumber" })
        </div>
        <div class="col-md-2 no-left-padding " data-tooltip="tooltip" title="Found From">
            <div class="input-group">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </div>
                <input id="orderedFrom" name="orderedFrom" type="text" class="form-control input-md" placeholder="From" value="@ViewBag.OrderedFrom">
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                <div class="input-group-addon">
                    <a href="#" id="" class="btnClearSearch" data-tooltip="tooltip" title="Clear Search"><span class="glyphicon glyphicon-remove"></span></a>
                </div>
            </div>
        </div>
        <div class="col-md-2 no-left-padding " data-tooltip="tooltip" title="Found To">
            <div class="input-group">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </div>
                <input id="orderedTo" name="orderedTo" type="text" class="form-control input-md" placeholder="To" value="@ViewBag.OrderedTo">
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                <div class="input-group-addon">
                    <a href="#" id="" class="btnClearSearch" data-tooltip="tooltip" title="Clear Search"><span class="glyphicon glyphicon-remove"></span></a>
                </div>
            </div>
        </div>
        @*<div class="col-md-3 no-left-padding" id="divSearch" data-tooltip="tooltip" title="Search">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-search"></span>
                        </div>
                        <input type="hidden" id="searchType" name="searchType" value="basic" />
                        <input type="hidden" id="clearSessionId" name="clearSessionId" value="" />
                        <input type="text" id="searchString" name="searchString" class="form-control input-md" placeholder="Type to search" value="@ViewBag.searchString">
                        <div class="input-group-addon">
                            <a href="#" id="btnClearSearch" name="btnClearSearch" data-tooltip="tooltip" title="Clear Search"><span class="glyphicon glyphicon-remove"></span></a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-1" id="divTools" style="text-align:left">
                <button class="btn btn-default" href="#" data-toggle="modal" data-target="#searchModal" data-tooltip="tooltip" title="Search">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>*@
        <div class="col-md-1" id="divTools" style="text-align: left">
            <a href="@Url.Action("Settings", "Notification")" title="Settings" data-tooltip="tooltip" class="btn btn-default">
                <span class="fa fa-cog"></span>
            </a>
        </div>
    </div>
</form>

    <table class="table">
        <tr>
            <td>
                @Html.SortIdentifier(currentSort, "OrderNumber")
                @Html.ActionLink("#", "Index", columnSortParams1)
            </td>
            <td>
                @Html.SortIdentifier(currentSort, "CampaignName")
                @Html.ActionLink("Campaign Name", "Index", columnSortParams2)
            </td>
            <td>
                @Html.SortIdentifier(currentSort, "FoundAt")
                @Html.ActionLink("Found At", "Index", columnSortParams4)
            </td>
            <td>
                @Html.SortIdentifier(currentSort, "Problem")
                @Html.ActionLink("Problem", "Index", columnSortParams5)
            </td>
            <td>
                @Html.SortIdentifier(currentSort, "Problem Detail")
                @Html.ActionLink("Problem Detail", "Index", columnSortParams6)
            </td>
            <td>
                @Html.SortIdentifier(currentSort, "Status")
                @Html.ActionLink("Status", "Index", columnSortParams6)
            </td>
        </tr>

        @foreach (var item in Model)
        {
            var rowClass = item.QcRule == 2 || item.QcRule == 4 || item.QcRule == 6 || item.QcRule == 8 ? "btn-default" : (item.QcRule == 1 || item.QcRule == 10 || item.QcRule == 11) ? "btn-primary" : "btn-danger";

            <tr class="@rowClass">
                <td>
                    @(string.IsNullOrEmpty(item.SegmentNumber) ? item.OrderNumber : item.SegmentNumber) 
                </td>
                <td>
                    @item.CampaignName
                </td>
                <td>
                    @item.FoundAt
                </td>
                <td>
                    @item.QcRuleString
                </td>
                <td class="no-right-padding no-left-padding">
                    @item.Message
                </td>
                <td class="no-right-padding no-left-padding">
                    @item.Status
                </td>
            </tr>
        }

    </table>

    <div class="row">
        <div class="col-md-12 text-center">
            <div class="page-count">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            </div>
            <div class="tp-pagination">
                @Html.PagedListPager(Model, page => Url.Action("Index", new
       {
           page,
           sortOrder = ViewBag.CurrentSort,
           searchType = ViewBag.SearchType,
           basicString = ViewBag.BasicStringSearched,
           basicStatus = ViewBag.BasicStatusSearched,
           advancedStatus = ViewBag.AdvancedStatusSearched,
           advancedUser = ViewBag.AdvancedUserSearched,
           campaignName = ViewBag.CampaignName,
           isTested = ViewBag.IsTested,
           orderedFrom = ViewBag.OrderedFrom,
           orderedTo = ViewBag.OrderedTo,
           broadcastFrom = ViewBag.BroadcastFrom,
           broadcastTo = ViewBag.BroadcastTo
       }), new PagedListRenderOptions() { })
            </div>
        </div>
    </div>


    <script type="text/javascript">

        var wfp = wfp || {};

        $(document).ready(function () {

            $('#basicString').keypress(function (e) {
                if (e.which === 13) {
                    $('form#frmSearch').submit();
                    return false;
                }
            });

            $('.btnClearSearch').click(function () {
                debugger;
                wfp.reload('/Notification');
                return false;
            });

            $("#orderedFrom").datepicker({
                dateFormat: 'mm/dd/yy'
            }).on("change", function (e) {
                $('form#frmSearch').submit();
                return;
                });

            $("#orderedTo").datepicker({
                dateFormat: 'mm/dd/yy'
            }).on("change", function (e) {
                $('form#frmSearch').submit();
                return;
            });

            $("#basicOrderNumber").select2().on("change", function (e) {
                $('form#frmSearch').submit();
                return;
            });

            $("#basicStatus").select2().on("change", function (e) {
                $('form#frmSearch').submit();
                return;

            });

        });

    </script>

ADSDataDirect.Web/Views/Notification/Settings.cshtml
@using ADSDataDirect.Core.Entities
@using ADSDataDirect.Enums
@model  ADSDataDirect.Infrastructure.Db.SettingsVm
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var loggedInUser = Session["user"] as WfpUser;
    var isLoggedIn = loggedInUser != null;
    var isAdmin = loggedInUser != null && (loggedInUser.UserType == (int)UserType.Admin);

}

<h2>Settings<span class="small"></span></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">

            <div class="tabbable-panel">
                <div class="tabbable-line">
                    <ul class="nav nav-tabs ">
                        <li class="active">
                            <a href="#tab_default_1" data-toggle="tab">
                                Settings
                            </a>
                        </li>
                        <div class="pull-right" id="tools">
                            <button type="submit" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-saved"></span> Save</button>
                        </div>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_default_1">

                            <div class="row">
                                <div class="col-md-6">
                                    
                                    <div class="form-group">
                                        <label class="control-label col-md-5">IsAutoTracking</label>
                                        <div class="col-md-7">
                                            <div class="">
                                                <div class="btn-group" data-toggle="buttons" style="padding-bottom: 10px">
                                                    <label class="btn btn-primary">
                                                        @Html.RadioButtonFor(model => model.IsAutoProcessTracking, "True")Yes
                                                    </label>
                                                    <label class="btn btn-primary">
                                                        @Html.RadioButtonFor(model => model.IsAutoProcessTracking, "False")No
                                                    </label>
                                                </div>
                                                @Html.ValidationMessageFor(model => model.IsAutoProcessTracking, "", new {@class = "text-danger"})
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NotStartedInXHoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.NotStartedInXHoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NotStartedInXHoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NotHitOpenRateIn24HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.NotHitOpenRateIn24HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NotHitOpenRateIn24HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NotHitOpenRateIn72HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.NotHitOpenRateIn72HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NotHitOpenRateIn72HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NotHitClickRateIn24HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.NotHitClickRateIn24HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NotHitClickRateIn24HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.NotHitClickRateIn72HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.NotHitClickRateIn72HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.NotHitOpenRateIn72HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-6">
                                    
                                    <div class="form-group">
                                        <label class="control-label col-md-5">Send Notifications Emails</label>
                                        <div class="col-md-7">
                                            <div class="">
                                                <div class="btn-group" data-toggle="buttons" style="padding-bottom: 10px">
                                                    <label class="btn btn-primary">
                                                        @Html.RadioButtonFor(model => model.IsSendNotificationEmails, "True")Yes
                                                    </label>
                                                    <label class="btn btn-primary">
                                                        @Html.RadioButtonFor(model => model.IsSendNotificationEmails, "False")No
                                                    </label>
                                                </div>
                                                @Html.ValidationMessageFor(model => model.IsSendNotificationEmails, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <br /><br />    
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ExceededOpenRateIn24HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.ExceededOpenRateIn24HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ExceededOpenRateIn24HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ExceededOpenRateIn72HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.ExceededOpenRateIn72HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ExceededOpenRateIn72HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ExceededClickRateIn24HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.ExceededClickRateIn24HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ExceededClickRateIn24HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ExceededClickRateIn72HoursValue, htmlAttributes: new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.EditorFor(model => model.ExceededClickRateIn72HoursValue, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ExceededOpenRateIn72HoursValue, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>

            <br /><br />

        </div>
    </div>

}
<script type="text/javascript">

    var wfp = wfp || {};

    $(function () {
        $("input[name='IsAutoProcessTracking']:checked").closest("label.btn").addClass("active");
        $("input[name='IsSendNotificationEmails']:checked").closest("label.btn").addClass("active");
    });
</script>